function [out] = longAnimShortAnim()

% Functoin returns short and long clip match
longClipOrder = [424:433]'; 
shortClipOrder =  [82,86; ...
                         83, 87; ...
                         90,92; ...
                         91, 93; ...
                         92, 88;...
                         93, 89;...
                         86, 90;...
                         87, 91;...
                         88, 82;...
                         89, 83];

                     
out = [longClipOrder shortClipOrder];

end

